webmaster_password: "87654321q"
repluser_password: "12345678q"
barman_password: "14253678q"
ansible_user: vagrant
ansible_private_key_file: ".vagrant/machines/{{ ansible_hostname }}/virtualbox/private_key"
