- name: install packages
  yum: 
    name: epel-release
    state: present
    update_cache: true

- name: install node-exporter
  yum: 
    name: wget
    state: present
    update_cache: true

- name: Add node-exporter user
  user:
    name: node-exporter 
    state: present

- name: copy node-exporter bin
  copy:
    src: node-exporter
    dest: /usr/local/bin/node-exporter
    owner: node-exporter
    group: node-exporter
    mode: '0744'   

- name: copy node-exporter service
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'  

- name: start node-exporter service
  systemd:
    name: node-exporter
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Copy timezone
  copy:
    src: "/usr/share/zoneinfo/Europe/Moscow"
    dest: /etc/localtime
    remote_src: yes

- name: load filebeat.repo
  copy:
    src: "filebeat.repo"
    dest: /etc/yum.repos.d/kibana.repo
    owner: root
    group: root
    mode: '0644'

- name: install chrony
  yum:
    name: chrony
    state: present
    update_cache: true

- name: restart chronyd
  systemd:
    name: chronyd
    enabled: yes
    state: restarted

- name: Add sysctl rules
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: "{{ sysctl }}"
