version: '3.9'

services:

  database:
    image: postgres:14.5
    env_file:
      - .env_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    build: .
    command: python /website/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/website
    ports:
      - "8000:8000"
    env_file:
      - .env_dev
    depends_on:
      - database

volumes:
  postgres_data_dev: