version: '3.3'

services:
  web:
    build: .
    command: python /website/manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    volumes:
      - .:/website:Z
    env_file:
      - .env_prod
    networks:
      - todo-network
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: todo-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
    ports:
      - "8070:80"
    networks:
      - todo-network
networks:
  todo-network:
