version: '3.3'

services:
  web:
    build: .
    command: python /website/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/website:Z
    env_file:
      - .env_prod
    networks:
      todo-network:
        ipv4_address: 172.21.0.3
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: todo-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
    ports:
      - "8080:80"
      - "443:443"
    networks:
      todo-network:
        ipv4_address: 172.21.0.2

networks:
  todo-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16
