version: '3.3'

services:
  web:
    build: .
    command: python /website/manage.py runserver 0.0.0.0:8000
    logging:
      driver: "json-file"
    volumes:
      - .:/website:Z
    ports:
      - "80:8000"
    env_file:
      - .env_prod