version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: todo-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./nginx/nginx.log:/var/log/nginx/nginx.log:Z
      - /vagrant/ansible/roles/nginx/files/ssl.key:/etc/nginx/certs/ssl.key:Z
      /vagrant/ansible/roles/nginx/files/ssl.crt:/etc/nginx/certs/ssl.crt:Z
    ports:
      - "8080:80"
      - "443:443"