- name: install packages
  yum: 
    name: 
      - http://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    update_cache: true

- name: install barman
  yum: 
    name: 
      - barman
      - postgresql14
    state: present
    update_cache: true   
    
- name: Copy barman.conf
  template:
    src: templates/barman.conf.j2
    dest: /etc/barman.conf
    
- name: Copy config
  template:
    src: templates/pg.conf.j2
    dest: /etc/barman.d/pg.conf

- name: Start barman
  shell: barman cron && barman receive-wal --create-slot pg
  
- name: Start barman
  shell: barman switch-xlog --force --archive pg
  
- name: Add crontab
  shell: echo "*/30 * * * *   barman /usr/bin/barman backup pg" >> /etc/crontab