version: '2'
 
networks:
    monitor:
        driver: bridge
        ipam:
        config:
            - subnet: 172.21.0.0/16

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
            - ./node_down.yml:/etc/prometheus/node_down.yml:Z
        ports:
            - "9090:9090"
        networks:
            monitor:
                ipv4_address: 172.21.0.2
    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        ports:
            - 3000:3000
        networks:
            monitor:
                ipv4_address: 172.21.0.3