global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
 
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "node_down.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"
 
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'master'
    static_configs:
      - targets: ["{{ hostvars['master']['ansible_host'] }}:9100"]
 
  - job_name: 'slave'
    static_configs:
      - targets: ["{{ hostvars['slave']['ansible_host'] }}:9100"]

  - job_name: 'nginx'
    static_configs:
      - targets: ["{{ hostvars['nginx']['ansible_host'] }}:9100"]

  - job_name: 'web'
    static_configs:
      - targets: ["{{ hostvars['web']['ansible_host'] }}:9100"]

  - job_name: 'backup'
    static_configs:
      - targets: ["{{ hostvars['backup']['ansible_host'] }}:9100"]

