- name: install packages
  yum: 
    name: 
      - iptables
      - iptables-services
      - python-pip
      - python-setuptools
      - libsemanage-python
      - audispd-plugins
      - filebeat
    state: present
    update_cache: true

- name: Install pexpect
  pip:
    name: pexpect

- name: Set httpd_can_network_connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Set httpd_setrlimit
  seboolean:
    name: httpd_setrlimit
    state: yes
    persistent: yes

- name: Create ssl cert
  expect: 
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /vagrant/ansible/roles/nginx/files/ssl.key -out /vagrant/ansible/roles/nginx/files/ssl.crt
    timeout: null
    responses: 
      '.*Country Name .*': "ru"
      '.*State or Province.*': "sankt-peterburg" 
      '.*Locality Name.*': "City" 
      '.*Organization Name.*': "Otus" 
      '.*Organizational Unit.*': "linux-administrator" 
      '.*Common Name.*': "otusproject.som" 
      '.*Email Address.*': "1@1.ru" 

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Check certs dir
  file: 
    path: /etc/nginx/certs
    state: directory

- name: Add ssl_key
  copy:
    dest: /etc/nginx/certs/ssl.key
    src: /vagrant/ansible/roles/nginx/files/ssl.key
    remote_src: yes
    group: root
    owner: root
    mode: '0644'

- name: Add ssl_crt
  copy:
    dest: /etc/nginx/certs/ssl.crt
    src: /vagrant/ansible/roles/nginx/files/ssl.crt
    remote_src: yes
    group: root
    owner: root
    mode: '0644'    

- name: copy myconf.conf
  copy:
    dest: /etc/nginx/conf.d/myconf.conf
    src: /vagrant/ansible/roles/nginx/files/myconf.conf
    group: root
    owner: root
    mode: '0644'
    remote_src: yes

- name: copy nginx.conf
  copy:
    dest: /etc/nginx/nginx.conf
    src: /vagrant/ansible/roles/nginx/files/nginx.conf
    group: root
    owner: root
    mode: '0644'
    remote_src: yes

- name: Add audit.rules
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: |
      -w /etc/nginx/nginx.conf -p wa -k nginx_conf
      -w /etc/nginx/cond.d/ -p wa -k nginx_conf

- name: load auditd.conf
  copy:
    src: "auditd.conf"
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: '0644'

- name: load au-remote.conf
  copy:
    src: "au-remote.conf"
    dest: /etc/audisp/plugins.d/au-remote.conf
    owner: root
    group: root
    mode: '0644'

- name: load audisp-remote.conf
  template:
    src: "audisp-remote.conf.j2"
    dest: /etc/audisp/audisp-remote.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart auditd
  shell: service auditd restart


- name: Test nginx.conf
  command: "nginx -t"
  register: test
 
- name: Test nginx.conf successful
  debug: 
    msg: success

- name: start nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: load filebeat.yml
  copy:
    src: "filebeat.yml"
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'


- name: Active nginx.yml
  copy:
    src: nginx.yml
    dest: /etc/filebeat/modules.d/nginx.yml 

- name: restart filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: restarted

- name: copy iptables config
  copy:
    src: iptables
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0600

- name: start and enable iptables service
  service:
    name: iptables
    state: restarted
    enabled: true

- name: import index pattern
  shell: "curl -X POST localhost:5601/api/saved_objects/_import?createNewCopies=true -H "kbn-xsrf: true" --form file=@myweb.ndjson"
  args:
    chdir: /vagrant/ansible/roles/backup/files/
