- name: install packages
  yum: 
    name: 
      - iptables
      - iptables-services
      - python-pip
      - python-setuptools
    state: present
    update_cache: true

- name: Install pexpect
  pip:
    name: pexpect

- name: start docker
  systemd:
    name: docker
    enabled: yes
    state: restart
    daemon_reload: yes

- name: Create ssl 
  expect: 
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /vagrant/ansible/roles/nginx/files/ssl.key -out /vagrant/ansible/roles/nginx/files/ssl.crt
    timeout: null
    responses: 
      '.*Country Name .*': "ru"
      '.*State or Province.*': "sankt-peterburg" 
      '.*Locality Name.*': "City" 
      '.*Organization Name.*': "Otus" 
      '.*Organizational Unit.*': "linux-administrator" 
      '.*Common Name.*': "otusproject.som" 
      '.*Email Address.*': "1@1.ru" 

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Check cert dir
  file: 
    path: /etc/nginx/certs
    state: directory

- name: Add ott_tricolor_tv_bundle_crt
  copy:
    dest: /etc/nginx/certs/ssl.crt
    src: /vagrant/ansible/roles/nginx/files/ssl.key
    remote_src: yes
    group: root
    owner: root
    mode: '0644'

- name: Add ott_tricolor_tv_bundle_crt
  copy:
    dest: /etc/nginx/certs/ssl.crt
    src: /vagrant/ansible/roles/nginx/files/ssl.crt
    remote_src: yes
    group: root
    owner: root
    mode: '0644'    

- name: copy nginx.conf
  copy:
    dest: /etc/nginx/conf.d/mds_pos_prod_proxy.conf
    src: /vagrant/ansible/roles/nginx/files/nginx.conf
    group: root
    owner: root
    mode: '0644'
    remote_src: yes

- name: Test nginx.conf
  command: "nginx -t"
  register: test
 
- name: Test nginx.conf successful
  debug: 
    msg: success

- name: start nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: copy iptables config
  copy:
    src: iptables
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0600

- name: start and enable iptables service
  service:
    name: iptables
    state: restarted
    enabled: true

