- name: install packages
  yum: 
    name: 
      - docker-compose
      - docker
    state: present
    update_cache: true

- name: start docker
  systemd:
    name: docker
    enabled: yes
    state: restarted

- name: Docker-compose up
  command: docker-compose -f docker-compose.yml up -d
  args:
    chdir: /vagrant/ansible/roles/web/files/

- name: start migration 
  shell: docker-compose -f docker-compose.yml exec web python manage.py migrate
  args:
    chdir: /vagrant/ansible/roles/web/files/
  ignore_errors: true