- name: install packages
  yum: 
    name: 
      - docker-compose
      - docker
      - audispd-plugins
      - filebeat
    state: present
    update_cache: true

- name: load filebeat.yml
  copy:
    src: "filebeat.yml"
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'


- name: Active nginx.yml
  copy:
    src: /etc/filebeat/modules.d/nginx.yml.disabled
    dest: /etc/filebeat/modules.d/web.yml
    remote_src: yes 


- name: restart filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: restarted

- name: start docker
  systemd:
    name: docker
    enabled: yes
    state: restarted

- name: Docker-compose up
  command: docker-compose -f docker-compose.yml up -d
  args:
    chdir: /vagrant/ansible/roles/web/files/

- name: start migration 
  shell: docker-compose -f docker-compose.yml exec web python manage.py migrate
  args:
    chdir: /vagrant/ansible/roles/web/files/
  ignore_errors: true

- name: load filebeat.yml
  copy:
    src: "filebeat.yml"
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'

- name: Active web.yml
  copy:
    src: web.yml
    dest: /etc/filebeat/modules.d/nginx.yml 

- name: restart filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: restarted