- hosts: all
  become: yes
  roles:
    - role: roles/prepare

- hosts: postgres
  become: yes
  roles:
    - role: roles/postgres

- hosts: backup
  become: yes
  roles:
    - role: roles/backup

- hosts: nginx
  become: yes
  roles:
    - role: roles/nginx    

- hosts: web
  become: yes
  roles:
    - role: roles/web    
