- name: load rsyslog.conf
  copy:
    src: "rsyslog.conf"
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'


- name: Restart rsyslog
  systemd:
    name: rsyslog
    enabled: yes
    state: restarted


- name: Config auditd
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: '##tcp_listen_port = 60'
    line: 'tcp_listen_port = 60'
    state: present


- name: Restart auditd
  shell: service auditd restart

- name: Install java
  yum:
    name: java-1.8.0
    state: present
